name: Deploy to Google Cloud Storage

on:
  workflow_dispatch:
    inputs:
      run_optional_job:
        description: 'Deploy to Google Cloud Storage'
        required: true
        default: false
        type: boolean

# Required for Workload Identity Federation
permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_optional_job == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Authenticate to Google Cloud
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          # Use Workload Identity Federation (Recommended)
          # 'projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_NAME/providers/PROVIDER_NAME'
          workload_identity_provider: 'projects/1053952427712/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'service-1053952427712@gs-project-accounts.iam.gserviceaccount.com'

      # 2. Upload to Cloud Storage
      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'out/'  # The local folder or file to upload
          destination: '1234webtool' # Target bucket and optional prefix
          parent: false  # If false, skips creating the 'dist' folder inside the bucket
          gzip: true     # Enable gzip compression for the upload
          process_gcloudignore: false # Process .gcloudignore file to exclude files from upload